version: '3.8'
services:
  db-dev:
    container_name: db-dev
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sdpdocker
      MONGO_INITDB_ROOT_PASSWORD: 123456docker
    ports:
      - 27017:27017
    volumes:
      - db-dev:/data/db
  
  api-dev:
    container_name: api-dev
    build: .
    restart: always
    ports:
      - '8081:5000'
    image: api
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://db-dev:27017
      CONNECTION_STRING_DOCKER: mongodb://sdpdocker:123456docker@db-dev:27017
      DB_NAME: db_dev
    depends_on:
      - db-dev 

  db-test:
    container_name: db-test
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sdpdocker2
      MONGO_INITDB_ROOT_PASSWORD: 123456docker
    ports:
      - 27020:27017
    volumes:
      - db-test:/data/db
  
  api-test:
    container_name: api-test
    build: .
    restart: always
    ports:
      - '8082:5000'
    image: api
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://db-test:27020
      CONNECTION_STRING_DOCKER: mongodb://sdpdocker:123456docker@db-test:27020
      DB_NAME: db_test
    depends_on:
      - db-test

volumes:
  db-dev:
  db-test: